### ISSUE TITLE
不在以下合法域名列表中 wx.request合法域名配置

### ISSUE THREAD

**Issue by Vcxtan** [yll2wcf/wechat-weapp-lifeTools#2]
请问一下，通过wx.request请求的时候，总是报“不在以下合法域名列表中“ 这样的错误，在mp.weixin.com中添加合法的域名，可以解决，但是我添加”http://apistore.baidu.com“之后，还是不行，请问您的mp.weixin.com
中如何添加的。谢谢

**Comment by yll2wcf** [comment]
最近一直在做公司项目, sorry没有维护这个项目,  现在新版本小程序貌似不允许 http链接了, 代码只是仅供参考了, 没法使用了

**Comment by yll2wcf** [comment]
最近一直在做公司项目, sorry没有维护这个项目,  现在新版本小程序貌似不允许 http链接了, 代码只是仅供参考了, 没法使用了

**Comment by yll2wcf** [comment]
最近一直在做公司项目, sorry没有维护这个项目,  现在新版本小程序貌似不允许 http链接了, 代码只是仅供参考了, 没法使用了

**Comment by yll2wcf** [comment]
最近一直在做公司项目, sorry没有维护这个项目,  现在新版本小程序貌似不允许 http链接了, 代码只是仅供参考了, 没法使用了

**Comment by yll2wcf** [comment]
最近一直在做公司项目, sorry没有维护这个项目,  现在新版本小程序貌似不允许 http链接了, 代码只是仅供参考了, 没法使用了

**Comment by yll2wcf** [comment]
最近一直在做公司项目, sorry没有维护这个项目,  现在新版本小程序貌似不允许 http链接了, 代码只是仅供参考了, 没法使用了

**Comment by yll2wcf** [comment]
最近一直在做公司项目, sorry没有维护这个项目,  现在新版本小程序貌似不允许 http链接了, 代码只是仅供参考了, 没法使用了

**Comment by yll2wcf** [comment]
最近一直在做公司项目, sorry没有维护这个项目,  现在新版本小程序貌似不允许 http链接了, 代码只是仅供参考了, 没法使用了

**Comment by yll2wcf** [comment]
最近一直在做公司项目, sorry没有维护这个项目,  现在新版本小程序貌似不允许 http链接了, 代码只是仅供参考了, 没法使用了

**Comment by yll2wcf** [comment]
最近一直在做公司项目, sorry没有维护这个项目,  现在新版本小程序貌似不允许 http链接了, 代码只是仅供参考了, 没法使用了
